name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'

categories:
  - title: 'Features'
    labels:
      - 'feat'
      - 'enhancement'
      - 'pages'
      - 'styles'
  - title: 'Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: 'Breaking Changes'
    labels:
      - 'breaking-changes'
  - title: 'Maintenance'
    labels:
      - 'analytics'
      - 'chore'
      - 'documentation'
      - 'refactor'
      - 'workflow'
    collapse-after: 5

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.

version-resolver:
  major:
    labels:
      - 'release:major'
  minor:
    labels:
      - 'release:minor'
  patch:
    labels:
      - 'release:patch'
  default: patch

exclude-labels:
  - 'release:changelog'
  - 'release:skip'

autolabeler:
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/fix/i'

  - label: 'chore'
    branch:
      - '/chore\/.+/'
      - '/ci\/.+/'
    title:
      - '/chore/i'
      - '/ci/i'

  - label: 'feat'
    title:
      - '/feat/i'
    branch:
      - '/feat\/.+/'
    body:
      - '/\/enhancement\//'

  - label: 'test'
    branch:
      - '/test\/.+/'
    title:
      - '/test/i'

  - label: 'refactor'
    branch:
      - '/refactor\/.+/'
    title:
      - '/refactor:/i'

template: |
  ## What's Change
  **Release Notes**: [$RESOLVED_VERSION]

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION
